name: Docker Build and Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Save Version Number
        run: echo "${{ github.run_number }}" > VERSION

      - name: Build and Push Docker Image
        run: |
          VERSION=$(cat VERSION)
          docker build -t bharath415/node:$VERSION .
          docker push bharath415/node:$VERSION

      - name: Upload Version File
        uses: actions/upload-artifact@v4
        with:
          name: version-file
          path: VERSION
