name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Read and increment version
        id: version
        run: |
          if [ ! -f VERSION ]; then
            echo "1.0.0" > VERSION
          fi

          CURRENT_VERSION=$(cat VERSION)
          echo "Current version: $CURRENT_VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          PATCH=${PATCH:-0}

          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "New version: $NEW_VERSION"

          echo "$NEW_VERSION" > VERSION
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: bharath415/node:${{ env.VERSION }}

      - name: Upload VERSION file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: version-file
          path: VERSION
